name: Kevin Doole
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Kevin Doole
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a7eef4'
    - '#040000'
    - '#7e614f'
    - '#d8ac7b'
    - '#f7da9e'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
