name: Kevin Doole
favicon: null
layout_spectrum: 0.29602362192235887
typography_spectrum: 0.4028826418798417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.96831617038697
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
