title: Kevin Doole
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0
  brandStrength: 0.3154122
  lightness: 1
  brandColors:
    - '#a7eef4'
    - '#040000'
    - '#7e614f'
    - '#d8ac7b'
    - '#f7da9e'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: UA-76242018-1
  facebook: null
name: Kevin Doole
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9301075
layout_spectrum: 0.2706093
